spring.application.name=be-ecommerce-naranjogianino
spring.datasource.url=jdbc:mysql://localhost:3306/db-ecommerce-naranjogianino?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-autp=update
spring.jpa.show-sql=true